# Generated by Django 4.2.7 on 2023-11-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_rating_product_average_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='average_rating',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
